### ISSUE TITLE
wrong tweak class?

### ISSUE THREAD

**Issue by supertassu** [HyperiumClient/Hyperium-Repo#1]
https://github.com/HyperiumClient/Hyperium-Repo/blob/master/installer/versions.json#L13

**Comment by 9Y0** [comment]
It looks right to me. They have some stuff written in kotlin so that's maybe why you couldn't find it

https://github.com/HyperiumClient/Hyperium/blob/master/src/main/kotlin/cc/hyperium/launch/HyperiumTweaker.kt

**Comment by supertassu** [comment]
The class that you linked is `cc.hyperium.launch.HyperiumTweaker`, the one in versions file that I linked is `com.hcc.launch.HyperiumTweaker`.

**Comment by supertassu** [comment]
fixed in `1a4607f`
