### ISSUE TITLE
jxbrowser-natives-6.19.1-natives-windows.jar

### ISSUE THREAD

**Issue by RamDz** [HyperiumClient/Hyperium-Repo#5]
Name: jxbrowser-natives-6.19.1-natives-windows.jar
URL: https://libraries.minecraft.net/cc/hyperium/libs/jxbrowser-natives/6.19.1/jxbrowser-natives-6.19.1-natives-windows.jar
Error details: HTTP 404: Not Found
Filename on disk: 3217-af2e-0088-f7b5
Path: C:\Users\\AppData\Local\Temp\3217-af2e-0088-f7b5
Exists: file
this is what minecraft says when i launch the client

**Comment by dxf** [comment]
Delete all hyperium related files/folders, and download a fresh copy.

**Comment by RamDz** [comment]
@VRCube no it didin't

**Comment by Sk1er** [comment]
This has been removed from the client. Closing issue.
